config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :gardens, only: [:index, :show] do
    resources :plants, only: [:create]
  end
  resources :plants, only: [:destroy] do
    resources :plant_tags, only: [:new, :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord
  has_many :plants, dependent: :destroy

  validates :name, presence: true
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden
  has_many :plant_tags, dependent: :destroy
  has_many :tags, through: :plant_tags

  validates :name, presence: true

end

app/models/plant_tag.rb
class PlantTag < ApplicationRecord
  belongs_to :plant
  belongs_to :tag


  validates :tag, uniqueness: { scope: :plant,
    message: "only 1 identical tag" }
end

app/models/tag.rb
class Tag < ApplicationRecord
  # has_many :plant_tags,
  # has_many :plants, through: :plant_tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  def index
    @gardens = Garden.all
  end

  def show
    @garden = Garden.find(params[:id])
    @plant = Plant.new
  end
end

app/controllers/plant_tags_controller.rb
class PlantTagsController < ApplicationController
  before_action :plant_tag_params, only: [:create]

  def new
    @plant = Plant.find(params[:plant_id])
    @plant_tag = PlantTag.new
  end

  def create
    @plant = Plant.find(params[:plant_id])

    # params[:plant_tag][:tag].reject(&:blank?) => me permet d'enlever la string vide dans le tag
    # On n'aurait pas eu besoin de faire ça avec l'option include_hidden: false dans notre form (cf. new.html.erb)

    tags = Tag.find(params[:plant_tag][:tag].reject(&:blank?))


    tags.each do |tag|
      plant_tag = PlantTag.new(tag: tag, plant: @plant)
      plant_tag.save
    end

    redirect_to garden_path(@plant.garden)
  end

  private

  def plant_tag_params
    params.require(:plant_tag).permit(:tag_id)
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def create
    @garden = Garden.find(params[:garden_id])
    @plant = Plant.new(plant_params)
    @plant.garden = @garden
    if @plant.save
      redirect_to garden_path(@garden)
    else
      render 'gardens/show'
    end
  end

  def destroy
    @plant = Plant.find(params[:id])
    @plant.destroy
    redirect_to garden_path(@plant.garden)
  end

  private

  def plant_params
    params.require(:plant).permit(:name, :image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plant_tags_helper.rb
module PlantTagsHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/gardens/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h1>Tous les jardins :</h1>
  <ul>
    <% @gardens.each do |garden| %>
      <li><%= link_to garden.name, garden_path(garden) %></li>
    <% end %>
  </ul>
</div>

app/views/gardens/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @garden.banner_url %>);">
  <div class="container">
    <h1><%= @garden.name %></h1>
  </div>
</div>

<div class="container cards">
  <% @garden.plants.each do |plant| %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= plant.image_url %>)">
      <%= link_to plant.name, new_plant_plant_tag_path(plant) %>
      <div class="card-tags">
        <% plant.tags.each do |tag| %>
          <span><%= tag.name %></span>
        <% end %>
      </div>
      <%= link_to '+', plant_path(plant), method: :delete, class: "card-destroy" %>
    </div>
  <% end %>
</div>

<div class="container">
  <h2>Ajouter une plante</h2>

  <%= simple_form_for [@garden, @plant] do |f| %>
    <%= f.input :name %>
    <%= f.input :image_url %>
    <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParksAndPlants</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plant_tags/create.html.erb
<h1>PlantTags#create</h1>
<p>Find me in app/views/plant_tags/create.html.erb</p>

app/views/plant_tags/new.html.erb
<div class="container">
  <h1>Add a tag for <%= @plant.name %></h1>
  <%= simple_form_for [@plant, @plant_tag] do |f| %>
    <%= f.input :tag, collection: Tag.all, input_html: {multiple: true, class: "multiple-select"} %>
    <!-- Ci-dessous, notez la version avec l'option include_hidden: false, qui nous permet d'enlever la string vide dans les params[:plant_tag][:tag] -->
    <%#= f.input :tag, collection: Tag.all, input_html: {multiple: true}, include_hidden: false %>
    <%= f.submit "add the tag", class: "btn btn-success" %>
  <% end %>
</div>

<!-- formulaire -->